version: '2.4'

services:
    postgres:
      environment:
        PGDATA: /data
      volumes:
        - postgres_data:/data
    redis: 
      volumes:
        - redis_data:/data

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true